#!/usr/bin/env bash
# Authors: Baibhav Anand Jha
# Documentation: github.com/baibhavanand/Fbuid

echo "
		  _         ___  _  
		 |_ |_  | |  |  | \ 
		 |  |_) |_| _|_ |_/ 
					                    
"
echo " 
   -Extract UserIDs From Public Facebook Accounts-
      
---Made With Love By - Baibhav | Twitter : @spongebhav---"
                                                     
while getopts u:f:h: flag
do
	case "${flag}" in
		u) nameinput=${OPTARG};;
		f) filename=${OPTARG};;
		h) help=${OPTARG};
	esac
done

			

function getUserId() {
	
	is_bsd=`grep -V | grep BSD`
	if [[ $is_bsd == *"BSD"* ]]; then
		local userid=`curl -L -s https://www.facebook.com/$1 | sed -e 's/}/\'$'\n/g; s/\"//g' | grep 'entity_id:[0-9]*' | awk -F":"  '{print $10}'`
		echo "$userid"
	else
		local userid=`curl -L -s https://www.facebook.com/$1 | grep -o -P '(?<=entity_id":").*?(?="})'`;
		echo "$userid"
	fi
}

function renderResult() {
	if [ "$2" == "" ]; then
		echo "Facebook is probably blocking our request. Please try again later."
	else	
		echo -n "The UserID for $1 is: $2 "
	fi	
}

if [ "$1" == "" ];
then
echo "
"
echo -n "Enter Username: "; read username
echo "
"
	userid="$(getUserId $username)"
	renderResult $username $userid
echo "
"
fi

if [ "$filename" != "" ];
then
echo "
"
	while read line; do
		useridforline="$(getUserId $line)"
		renderResult $line $useridforline
		printf "\n"
done < $filename
echo "
"
fi

if [ "$nameinput" != "" ];
then
echo "
"
	userIDfornameinput="$(getUserId $nameinput)"
	renderResult $nameinput $userIDfornameinput
echo "
"
fi

if [ "$filename" == "" ] && [ "$nameinput" == "" ] && [ "$1" != "" ]; then
	echo "
Note : FbUID will only work for public Facebook accounts. 

Usage:

fbuid (without any arguments)      will present you with a prompt to enter username.
-u  To specify username
-f  To specify full path to text file containing usernames"
echo "
"
fi
